EcommerceManga/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('', include('tienda.urls')),
    path('carrito/', include('carts.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove')
]

templates/snippets/add.html
<form action="{% url 'carts:add' %}" method="post">
    {% csrf_token %}

    <input type ="hidden" name="product_id" value="{{ p.idProducto }}">
    <div class="">
        <button type="button" class="btn btn-info d-inline btnAoD" id="remove">-</button>
        <input type="text" value="1" class="form-control col-sm-1 d-inline" id="quantity" name="quantity" readonly>
        <button type="button" class="btn btn-info" id="add">+</button>
    </div>
    <button type="submit" class="btn btn-primary">Agregar al carrito</button>
</form>

<script>

    const add = document.getElementById('add')
    const remove = document.getElementById('remove')
    const quantity = document.getElementById('quantity')

    add.addEventListener('click', evento=>{
        boton = (evento.target.parentElement.querySelector(".btnAoD").dataset.id)
        console.log(boton)
       // quantity.value = parseInt(quantity.value) + 1
    })

    remove.addEventListener('click',function(){
        value = parseInt(quantity.value)

        if(value != 1){
            value = value -1 
        }
        quantity.value = value
    })


</script>

templates/snippets/remove.html
<form action="{% url 'carts:remove' %}" method="post">
    {% csrf_token %}

    <input type ="hidden" name="product_id" value="{{ producto.idProducto }}">
    <button type="submit" class="btn btn-link text-danger" style="padding:0px;">Eliminar</button>
</form>